### ISSUE TITLE
无法安装使用

### ISSUE THREAD

**Issue by Jacky-LinPeng** [DevaLee/cocoapods-binary-bel#1]
- 安装
`sudo gem install cocoapods-binary-bel

Successfully installed cocoapods-binary-bel-0.5.4
Parsing documentation for cocoapods-binary-bel-0.5.4
Done installing documentation for cocoapods-binary-bel after 0 seconds
1 gem installed`

- 查看已安装插件（未看到cocoapods-binary-bel）
`
pod plugins installed
    - cocoapods-binary-cache : 0.1.14 (pre_install and post_install hooks)
    - cocoapods-deintegrate  : 1.0.4
    - cocoapods-plugins      : 1.0.0
    - cocoapods-search       : 1.0.0
    - cocoapods-trunk        : 1.5.0
    - cocoapods-try          : 1.2.0
`
  - 使用
  `Your Podfile requires that the plugin `cocoapods-binary-bel` be installed. Please install it and try installation again.` 

- pod 版本
`1.11.2`

**Comment by DevaLee** [comment]
> * 安装
>   `sudo gem install cocoapods-binary-bel
> 
> Successfully installed cocoapods-binary-bel-0.5.4 Parsing documentation for cocoapods-binary-bel-0.5.4 Done installing documentation for cocoapods-binary-bel after 0 seconds 1 gem installed`
> 
> * 查看已安装插件（未看到cocoapods-binary-bel）
>   `
>   pod plugins installed
>   
>   * cocoapods-binary-cache : 0.1.14 (pre_install and post_install hooks)
>   * cocoapods-deintegrate  : 1.0.4
>   * cocoapods-plugins      : 1.0.0
>   * cocoapods-search       : 1.0.0
>   * cocoapods-trunk        : 1.5.0
>   * cocoapods-try          : 1.2.0
>     `
>   * 使用
>     `Your Podfile requires that the plugin `cocoapods-binary-bel` be installed. Please install it and try installation again.`
> * pod 版本
>   `1.11.2`

我可以正常安装和使用的
bel@beldeMacBook-Pro cocoapods-binary-bel % pod plugins installed                

Installed CocoaPods Plugins:
    - cocoapods-binary-bel  : 0.5.4 (pre_install hook)
    - cocoapods-deintegrate : 1.0.5
    - cocoapods-play        : 0.1.0
    - cocoapods-plugins     : 1.0.0
    - cocoapods-search      : 1.0.1
    - cocoapods-trunk       : 1.6.0
    - cocoapods-try         : 1.2.0

在ruby gem 托管平台也可以找到
  https://rubygems.org/search?query=cocoapods-binary-bel

你可以试下在 Podfile文件里面引用，看是否可以正常使用

**Comment by Jacky-LinPeng** [comment]
我安装成功了，但是查看安装列表的时候看不到，不知道是不是安装了其他插件导致的，直接在podfile里面使用会报错说我没安装该插件
`
[!] Your Podfile requires that the plugin cocoapods-binary-bel be installed. Please install it and try installation again.
`

**Comment by jingcaich** [comment]
确实存在这个问题
